
# alwayse use absolute paths

##### RESOURCES #####
mem: '32000'
threads: 1
partition: 'shortq'

##### GENERAL #####
annotation: /research/home/sreichl/projects/macroIC/config/CC001_dea_limma_annotation.csv
result_path: /nobackup/lab_bock/projects/macroIC/results/CC001/
project_name: CC001


##### DEA #####

# EXPLAINATION HERE
# also for blocing variable (block_var)
reference_levels:
    treatment: "UT"
    time: "0h"

##### AGGREGATION #####
# filters are applied to the DEA results and used for all outputs
filters:
    adj_pval: 0.05
    lfc: 0.1
    ave_expr: 0.1

##### VISUALIZATION #####

# parameters for https://bioconductor.org/packages/release/bioc/html/EnhancedVolcano.html
volcano:
    pCutoff: 0.05
    FCcutoff: 2
