
# alwayse use absolute paths

##### RESOURCES #####
mem: '32000'
threads: 1
partition: 'shortq'

##### GENERAL #####

# absolute path to annotation file, specified in config/README.md
annotation: /research/home/sreichl/projects/macroIC/config/CC001_dea_limma_annotation.csv

# (optional) absolute path to a feature annotation file with the first column as the used features (eg ENSEMBLE IDs) and "column" the annotated name (eg gene symbols). If not used leave empty "".
feature_annotation:
    path: /nobackup/lab_bock/projects/macroIC/results/CC001/counts/gene_annotation.csv
    column: "external_gene_name"

# absolute path to the result directory of the project/dataset
result_path: /nobackup/lab_bock/projects/macroIC/results/CC001/

# project/dataset name, used only in the report
project_name: CC001


##### DEA #####

# specifiy the reference levels that the comparisons are based on of all variables of interest here (eg treatment: "untreated").
reference_levels:
    treatment: "UT"
    time: "0h"

##### AGGREGATION #####
# score_formula is used to calculate a score for each gene and comparison (group) that can be used downstream e.g., for ranked GSEA
# eval based score calculation -> eval(parse(text=" "))
# DEA result dataframe is called: dea_results
# available numerical columns: logFC; AveExpr; t; P.Value; adj.P.Val; B
# common/popular example: "-log10(dea_results$P.Value)*sign(dea_results$logFC)"
# if not used leave empty: ""
score_formula: "-log10(dea_results$P.Value)*sign(dea_results$logFC)"

# filters are applied to the DEA results, which contain all results, and used for downstream outputs (eg feature lists, LFC matrix).
filters:
    adj_pval: 0.05
    lfc: 2
    ave_expr: 0

##### VISUALIZATION #####

# parameters for volcano plots powered by EnhancedVolcano (https://bioconductor.org/packages/release/bioc/html/EnhancedVolcano.html)
volcano:
    pCutoff: 0.05
    FCcutoff: 2
